steps:
- name: 'gcr.io/cloud-builders/bash:3.1.2' # O ':latest', pero probando con una versión específica.
  args:
  - 'echo'
  - 'IMAGE_NAME: ${_REGION}-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/ws:latest'
  id: 'Debug Image Name'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/ws:latest'
  - '.'
  id: 'Build Docker Image'

images:
- '${_REGION}-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/ws:latest'
options:
  logging: CLOUD_LOGGING_ONLY
