steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/ws:latest'
  - '.'
images:
- '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/ws:latest'
options:
  logging: CLOUD_LOGGING_ONLY
